### ISSUE TITLE
Time to switch to Java 7,8 and above?

### ISSUE THREAD

**Issue by bjonnh** [rdfhdt/hdt-java#100]
It is not possible to compile hdt-fuseki anymore with the source and target 1.6.

I changed it to 1.8, it compiles OK, but there are other errors when running it:

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/jena/sparql/lib/Metadata
	at org.apache.jena.tdb2.TDB2.<clinit>(TDB2.java:163)
	at org.apache.jena.tdb2.sys.InitTDB2.start(InitTDB2.java:28)
	at org.apache.jena.sys.JenaSystem.lambda$init$2(JenaSystem.java:117)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
	at org.apache.jena.sys.JenaSystem.forEach(JenaSystem.java:192)
	at org.apache.jena.sys.JenaSystem.forEach(JenaSystem.java:169)
	at org.apache.jena.sys.JenaSystem.init(JenaSystem.java:115)
	at arq.cmdline.CmdARQ.<clinit>(CmdARQ.java:31)
Caused by: java.lang.ClassNotFoundException: org.apache.jena.sparql.lib.Metadata
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 8 more

**Comment by mielvds** [comment]
Unfortunately, this means switching from the now deprecated Fuseki 1 to Fuseki 2, which is a seperate issue entirely. I don't have the bandwidth to do this migration, especially because the user base of HDT fuseki is pretty non-existent. The same behaviour can be achieved by using HDT-Jena in combination with some Fuseki2 code. 

A better would be to simple deprecate the Fuseki part of this repo all together.

**Comment by bjonnh** [comment]
This make sense, thanks.
