### ISSUE TITLE
Error when running hdt-fuseki

### ISSUE THREAD

**Issue by bjonnh** [rdfhdt/hdt-java#101]
HDT fuseki fails with 
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/jena/sparql/lib/Metadata
	at org.apache.jena.tdb2.TDB2.<clinit>(TDB2.java:163)
	at org.apache.jena.tdb2.sys.InitTDB2.start(InitTDB2.java:28)
	at org.apache.jena.sys.JenaSystem.lambda$init$2(JenaSystem.java:117)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
	at org.apache.jena.sys.JenaSystem.forEach(JenaSystem.java:192)
	at org.apache.jena.sys.JenaSystem.forEach(JenaSystem.java:169)
	at org.apache.jena.sys.JenaSystem.init(JenaSystem.java:115)
	at arq.cmdline.CmdARQ.<clinit>(CmdARQ.java:31)
Caused by: java.lang.ClassNotFoundException: org.apache.jena.sparql.lib.Metadata
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 8 more

**Comment by mielvds** [comment]
Cannot fix as explained in #100

**Comment by bjonnh** [comment]
This make sense, thanks.
