### ISSUE TITLE
java.lang.NegativeArraySizeException parsing Wikidata HDT file

### ISSUE THREAD

**Issue by janothan** [rdfhdt/hdt-java#104]
I downloaded the [Wikidata HDT data set](http://www.rdfhdt.org/datasets/). 
I try to load it using the following code:

```
HDT hdtDataSet = HDTManager.loadHDT(hdtFilePath);
```

When I run the program, I get the following exception after some minutes:

```
Exception in thread "main" java.lang.NegativeArraySizeException
	at org.rdfhdt.hdt.compact.sequence.SequenceLog64.load(SequenceLog64.java:350)
	at org.rdfhdt.hdt.triples.impl.BitmapTriples.load(BitmapTriples.java:359)
	at org.rdfhdt.hdt.hdt.impl.HDTImpl.loadFromHDT(HDTImpl.java:201)
	at org.rdfhdt.hdt.hdt.impl.HDTImpl.loadFromHDT(HDTImpl.java:214)
	at org.rdfhdt.hdt.hdt.HDTManagerImpl.doLoadHDT(HDTManagerImpl.java:34)
	at org.rdfhdt.hdt.hdt.HDTManager.loadHDT(HDTManager.java:66)
```

I am using:

```
        <dependency>
            <groupId>org.rdfhdt</groupId>
            <artifactId>hdt-java-core</artifactId>
            <version>2.1.1-SNAPSHOT</version>
        </dependency>
```

Remark: It does work with other data sets such as `Semantic Web Dog Food`.

**Comment by mielvds** [comment]
Hi @janothan , does it work in de cpp version?
