### ISSUE TITLE
Null pointer exception in BaseDictionary when values are not existing in triple store.

### ISSUE THREAD

**Issue by bjonnh** [rdfhdt/hdt-java#110]
2020-05-29 16:30:38.971 [qtp586917260-13] INFO  org.apache.jena.fuseki.Fuseki - [22] Query = PREFIX  n:    <https://rdf.napralert.org/>  SELECT DISTINCT  ?genus ?species ?organism ?pharmacology ?pha
rmacology_name ?qualitative_result_name WHERE   { ?organism ^n:has_organism ?pharmacy .     ?pharmacy  n:has_pharmacology  ?pharmacology .     ?pharmacology               n:name              ?pharma
cology_name     OPTIONAL       { ?pharmacy  n:has_qualitativeresult  ?qualitative_result .         ?qualitative_result                   n:name                ?qualitative_result_name       }     ?o
rganism  n:genusname   ?genus ;               n:speciesname  ?species     VALUES ( ?genus ?species ) {       ( "Rati" "Rata" )     }   } 
2020-05-29 16:30:39.249 [qtp586917260-13] WARN  org.apache.jena.fuseki.Fuseki - [22] RC = 500 : null
java.lang.NullPointerException: null
	at org.rdfhdt.hdt.dictionary.impl.BaseDictionary.getSection(BaseDictionary.java:192)
	at org.rdfhdt.hdt.dictionary.impl.BaseDictionary.idToString(BaseDictionary.java:217)
	at org.rdfhdt.hdtjena.NodeDictionary.translate(NodeDictionary.java:217)
	at org.rdfhdt.hdtjena.solver.StageMatchTripleID.translateBinding(StageMatchTripleID.java:185)
	at org.rdfhdt.hdtjena.solver.StageMatchTripleID.makeNextStage(StageMatchTripleID.java:122)
	at org.rdfhdt.hdtjena.solver.StageMatchTripleID.makeNextStage(StageMatchTripleID.java:55)
	at org.apache.jena.atlas.iterator.RepeatApplyIterator.hasNext(RepeatApplyIterator.java:48)
	at org.rdfhdt.hdtjena.util.IterAbortable.hasNext(IterAbortable.java:62)
	at org.apache.jena.atlas.iterator.RepeatApplyIterator.hasNext(RepeatApplyIterator.java:45)
	at org.rdfhdt.hdtjena.util.IterAbortable.hasNext(IterAbortable.java:62)
	at org.apache.jena.atlas.iterator.Iter$2.hasNext(Iter.java:347)
	at org.apache.jena.sparql.engine.iterator.QueryIterPlainWrapper.hasNextBinding(QueryIterPlainWrapper.java:53)
	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:114)
	at org.apache.jena.sparql.engine.iterator.QueryIterConvert.hasNextBinding(QueryIterConvert.java:58)
	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:114)
	at org.apache.jena.sparql.engine.iterator.QueryIterDistinct.getInputNextUnseen(QueryIterDistinct.java:113)
	at org.apache.jena.sparql.engine.iterator.QueryIterDistinct.hasNextBinding(QueryIterDistinct.java:72)
	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:114)
	at org.apache.jena.sparql.engine.iterator.QueryIteratorWrapper.hasNextBinding(QueryIteratorWrapper.java:39)
	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:114)
	at org.apache.jena.sparql.engine.iterator.QueryIteratorWrapper.hasNextBinding(QueryIteratorWrapper.java:39)
	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:114)
	at org.apache.jena.sparql.engine.ResultSetStream.hasNext(ResultSetStream.java:74)
	at org.apache.jena.sparql.engine.ResultSetCheckCondition.hasNext(ResultSetCheckCondition.java:55)
	at org.apache.jena.fuseki.servlets.SPARQLQueryProcessor.executeQuery(SPARQLQueryProcessor.java:326)
	at org.apache.jena.fuseki.servlets.SPARQLQueryProcessor.execute(SPARQLQueryProcessor.java:275)
	at org.apache.jena.fuseki.servlets.SPARQLQueryProcessor.executeWithParameter(SPARQLQueryProcessor.java:224)
	at org.apache.jena.fuseki.servlets.SPARQLQueryProcessor.execute(SPARQLQueryProcessor.java:199)
	at org.apache.jena.fuseki.servlets.ActionService.executeLifecycle(ActionService.java:58)
	at org.apache.jena.fuseki.servlets.SPARQLQueryProcessor.execGet(SPARQLQueryProcessor.java:79)
	at org.apache.jena.fuseki.servlets.ActionProcessor.process(ActionProcessor.java:33)
	at org.apache.jena.fuseki.servlets.ActionBase.process(ActionBase.java:55)
	at org.apache.jena.fuseki.servlets.ActionExecLib.execAction(ActionExecLib.java:106)
	at org.apache.jena.fuseki.server.Dispatcher.dispatchAction(Dispatcher.java:113)
	at org.apache.jena.fuseki.server.Dispatcher.process(Dispatcher.java:105)
	at org.apache.jena.fuseki.server.Dispatcher.dispatch(Dispatcher.java:99)
	at org.apache.jena.fuseki.servlets.FusekiFilter.doFilter(FusekiFilter.java:51)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.apache.jena.fuseki.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:285)
	at org.apache.jena.fuseki.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:248)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:503)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by mielvds** [comment]
Could you clean up you issue a bit? I can't tell what you mean

**Comment by bjonnh** [comment]
I have not been able to reproduce that reliably. I'll close it for now.
