### ISSUE TITLE
Can we make HDTCat work under windows?

### ISSUE THREAD

**Issue by fkleedorfer** [rdfhdt/hdt-java#127]
As stated in [HDTCat.java](https://github.com/rdfhdt/hdt-java/blob/b9ecbd1272846897d1c040f66fb9230a5e7d51bb/hdt-java-cli/src/main/java/org/rdfhdt/hdt/tools/HDTCat.java): HDTCat does not work under Windows.

However, I think I would really like it, and I'd be willing to do some digging, maybe we can fix it.

First, let me state my use case: The application we are developing is a desktop application, mostly for windows users (maybe some IOS, too). The application loads IFC files (architectural models) and uses [IFCtoRDF](https://github.com/pipauwel/IFCtoRDF) to generate triples, which it then keeps in-memory to query the model. Loading directly into an HDT model seems to save us some memory after it has been compressed. First, however, we have to load all triples into memory, which defines the minimum memory needed by the application, given the user wants to load a particular model.

The idea I experimented with was to map the triples into several smaller HDT models and then reduce that set into one using hdtcat, hoping that it still might, somehow, not be affected by the problem warned about in `HDTCat.java`. Well, turns out, it is. 

`java.io.RandomAccessFile.setLength()` produces this:

```
Generating dictionary
PREDICATES-------------------
java.io.IOException: Der Vorgang ist bei einer Datei mit einem geöffneten Bereich, der einem Benutzer zugeordnet ist, nicht anwendbar
	at java.base/java.io.RandomAccessFile.setLength(Native Method)
	at org.rdfhdt.hdt.util.disk.LongArrayDisk.resize(LongArrayDisk.java:98)
	at org.rdfhdt.hdt.compact.sequence.SequenceLog64BigDisk.resizeArray(SequenceLog64BigDisk.java:134)
	at org.rdfhdt.hdt.compact.sequence.SequenceLog64BigDisk.aggressiveTrimToSize(SequenceLog64BigDisk.java:209)
	at org.rdfhdt.hdt.dictionary.impl.FourSectionDictionaryCat.catSection(FourSectionDictionaryCat.java:387)
	at org.rdfhdt.hdt.dictionary.impl.FourSectionDictionaryCat.cat(FourSectionDictionaryCat.java:92)
	at org.rdfhdt.hdt.hdt.impl.HDTImpl.cat(HDTImpl.java:576)
	at at.researchstudio.sat.mmsdesktop.logic.IFC2ModelConverter.lambda$collectAsHdtModelMapReduce$4(IFC2ModelConverter.java:206)
	at java.base/java.util.stream.ReduceOps$2ReducingSink.accept(ReduceOps.java:123)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1694)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:558)
	at at.researchstudio.sat.mmsdesktop.logic.IFC2ModelConverter.collectAsHdtModelMapReduce(IFC2ModelConverter.java:176)
	at at.researchstudio.sat.mmsdesktop.logic.IFC2ModelConverter.lambda$readFromFile$1(IFC2ModelConverter.java:78)
	at java.base/java.lang.Thread.run(Thread.java:832)
```
After that, the hdtcat logic tries to close some temporary file, which also fails:
```
java.nio.file.FileSystemException: c:\tmp\ifc2hdt\1624979346429\16146e16-2065-4acd-ae2e-9cd45d542c07\section_buffer_4: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird
	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:92)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:274)
	at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
	at java.base/java.nio.file.Files.delete(Files.java:1146)
	at org.rdfhdt.hdt.dictionary.impl.FourSectionDictionaryCat.catSection(FourSectionDictionaryCat.java:417)
	at org.rdfhdt.hdt.dictionary.impl.FourSectionDictionaryCat.cat(FourSectionDictionaryCat.java:92)
	at org.rdfhdt.hdt.hdt.impl.HDTImpl.cat(HDTImpl.java:576)
	at at.researchstudio.sat.mmsdesktop.logic.IFC2ModelConverter.lambda$collectAsHdtModelMapReduce$4(IFC2ModelConverter.java:206)
	at java.base/java.util.stream.ReduceOps$2ReducingSink.accept(ReduceOps.java:123)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1694)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:558)
	at at.researchstudio.sat.mmsdesktop.logic.IFC2ModelConverter.collectAsHdtModelMapReduce(IFC2ModelConverter.java:176)
	at at.researchstudio.sat.mmsdesktop.logic.IFC2ModelConverter.lambda$readFromFile$1(IFC2ModelConverter.java:78)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

After all of this, two points:
1. If there is a good argument to be made against this idea, I'd like to hear it, it would save me a lot of work.
2. Is there any knowledge about this problem? Have you tried some digging of your own? Do you have suggestions on how to fix this?

**Comment by D063520** [comment]
Hi,

sorry I just saw now the issue .... yes this is also the problem we run into when writing hdtCat. As far as I remember: We are using mapped files and this is a feature that is not done by the JVM but by the operating system. For some reasons in Windows this is not working (or at least it was not at that time). I cannot find anymore the related ticked on the JDK issue tracker, so I do not know if it was resolved. But when I saw it it was open already since many years .... Maybe there is an easy bug fix but I do not know one.

Salut Dennis

I think it is something related to this https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6359560

**Comment by fkleedorfer** [comment]
After fixing HDTcat to work under Windows, I was able to evaluate the initial idea (question 1 in my initial post) - to a limited extent. Result: It might be the thing to do in situations where the available memory just isn't enough to generate a HDT file in one go. However, if it is possible to generate the whole HDT file in memory, it is much faster than the map-reduce approach (map to HDT chunks, reduce chunks using HDTcat). The difference in execution time is probably due to the many more filesystem accesses required in the map-reduce approach as each triple is processed multiple times. If the system could be changed to use in-memory data structures instead of memory mapped files for smaller amounts of data (i.e., data that fit in memory), this result might change as well.
