### ISSUE TITLE
Errors trying to process any other file format than NT

### ISSUE THREAD

**Issue by migalkin** [rdfhdt/hdt-java#29]
Compiled the HDT-Java library to transform a set of N3 and RDF/XML files to HDT.
When launching the script I get an error:

```
/hdt-java/hdt-java-package/target/hdt-java-package-2.0-distribution/hdt-java-package-2.0/bin# ./rdf2hdt.sh -rdftype n3 <n3 file> <hdt file>
Converting <n3file> to <hdt> as n3
Exception in thread "main" org.rdfhdt.hdt.exceptions.ParserException
	at org.rdfhdt.hdt.rdf.parsers.RDFParserRIOT.doParse(RDFParserRIOT.java:89)
	at org.rdfhdt.hdt.hdt.impl.TempHDTImporterOnePass.loadFromRDF(TempHDTImporterOnePass.java:100)
	at org.rdfhdt.hdt.hdt.HDTManagerImpl.doGenerateHDT(HDTManagerImpl.java:103)
	at org.rdfhdt.hdt.hdt.HDTManager.generateHDT(HDTManager.java:129)
	at org.rdfhdt.hdt.tools.RDF2HDT.execute(RDF2HDT.java:106)
	at org.rdfhdt.hdt.tools.RDF2HDT.main(RDF2HDT.java:167)
```

Tried all shell scripts available after the maven install, the error still exists.
The raw files can be imported in Virtuoso without any errors.
How do I process non-NT files using java lib?

**Comment by webdata** [comment]
Sorry, there as a small bug. Fixed in the last commit https://github.com/rdfhdt/hdt-java/commit/86d3a0486aaead2d1b5a179607d4c738c2195287. Please pull again and check if it is working now.
