### ISSUE TITLE
IllegalArgumentException when using BIND or VALUES with nonexisting resource

### ISSUE THREAD

**Issue by osma** [rdfhdt/hdt-java#37]
My example data is this triple:
```
<http://example.org/> <http://schema.org/name> "Example" .
```

I converted it to HDT and created an index. Then I executed this SPARQL query using hdtsparql.sh:
```
$ hdtsparql.sh example.hdt "SELECT * { BIND(<http://example.org/> AS ?s)  ?s ?p ?o }"
s,p,o
http://example.org/,http://schema.org/name,Example
```

So far so good. But when I change the bound URI to something nonexistent, I get an error:
```
$ hdtsparql.sh example.hdt "SELECT * { BIND(<http://example.org/2> AS ?s)  ?s ?p ?o }"
Exception in thread "main" java.lang.IllegalArgumentException: (?s,null)
	at org.rdfhdt.hdtjena.bindings.BindingHDTId.put(BindingHDTId.java:79)
	at org.rdfhdt.hdtjena.solver.HDTSolverLib$3.apply(HDTSolverLib.java:202)
	at org.rdfhdt.hdtjena.solver.HDTSolverLib$3.apply(HDTSolverLib.java:178)
	at org.apache.jena.atlas.iterator.Iter$4.next(Iter.java:308)
	at org.apache.jena.atlas.iterator.RepeatApplyIterator.hasNext(RepeatApplyIterator.java:47)
	at org.rdfhdt.hdtjena.util.IterAbortable.hasNext(IterAbortable.java:62)
	at org.apache.jena.atlas.iterator.Iter$4.hasNext(Iter.java:303)
	at org.apache.jena.sparql.engine.iterator.QueryIterPlainWrapper.hasNextBinding(QueryIterPlainWrapper.java:53)
	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:111)
	at org.apache.jena.sparql.engine.iterator.QueryIteratorWrapper.hasNextBinding(QueryIteratorWrapper.java:39)
	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:111)
	at org.apache.jena.sparql.engine.iterator.QueryIteratorWrapper.hasNextBinding(QueryIteratorWrapper.java:39)
	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:111)
	at org.apache.jena.sparql.engine.ResultSetStream.hasNext(ResultSetStream.java:74)
	at org.apache.jena.sparql.engine.ResultSetCheckCondition.hasNext(ResultSetCheckCondition.java:59)
	at org.apache.jena.sparql.resultset.CSVOutput.format(CSVOutput.java:81)
	at org.apache.jena.query.ResultSetFormatter.outputAsCSV(ResultSetFormatter.java:624)
	at org.rdfhdt.hdtjena.cmd.HDTSparql.main(HDTSparql.java:53)
```

I also tested via Fuseki and got the same errors.

Note that this variant, where BIND is not used, works fine:
```
SELECT * { <http://example.org/2> ?p ?o }
```

However, if I use VALUES, I can get the same error as with BIND:
```
SELECT * { VALUES ?s { <http://example.org/2> }  ?s ?p ?o }
```

**Comment by osma** [comment]
This also happens with literals, e.g.
```
$ hdtsparql.sh example.hdt 'SELECT * { VALUES ?o { "Example2" }  ?s ?p ?o }'
```
gives the same exception.

**Comment by osma** [comment]
[HDTSolverLib.java line 201](https://github.com/rdfhdt/hdt-java/blob/f36f561a6571e7663568ed2f9f249ee01aac6502/hdt-jena/src/main/java/org/rdfhdt/hdtjena/solver/HDTSolverLib.java#L201) comment says: `// Even put "does not exist" if it is null.`
This suggests to me that being able to store a `null` value is expected.

But actually [BindingHDTId.java line 78](https://github.com/rdfhdt/hdt-java/blob/2b7f1838c06ac872f4e7af4fa0da53678d2835e6/hdt-jena/src/main/java/org/rdfhdt/hdtjena/bindings/BindingHDTId.java#L78) checks for a `null` value and throws an exception.

Possible ways to fix:
1. Change BindingHDTId to allow a `null` value. Possibly dangerous, since it may cause breakage elsewhere.
2. Check for a `null` return value from the `getID` call and shortcut the loop with `continue`, as is done a few lines above in HDTSolverLib.

I'm unfamiliar with the codebase so I'm not sure about the consequences of these two options, but I can try to do a PR if it's useful. Hints welcome.

**Comment by osma** [comment]
I tested both approaches (1 and 2 in the previous comment) but they both give invalid results - the queries should return nothing for the example queries and data in the original issue report, but instead they return a binding `http://example.org/2,http://schema.org/name,Example`.
