### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by mladvladimir** [rdfhdt/hdt-java#72]
Hi, 
I tried next query from command line tool on the dataset DBLP 2017 from [http://www.rdfhdt.org/datasets/](url):
`SELECT DISTINCT ?property_type 
WHERE 
{?p a ?property_type . 
  ?s ?p ?o .} LIMIT 10
`

and what i got:

```
Exception in thread "main" java.lang.IndexOutOfBoundsException
	at org.rdfhdt.hdt.compact.sequence.SequenceLog64Map.get(SequenceLog64Map.java:190)
	at org.rdfhdt.hdt.triples.impl.PredicateIndexArray.getOccurrence(PredicateIndexArray.java:44)
	at org.rdfhdt.hdt.triples.impl.BitmapTriplesIteratorYFOQ.goToStart(BitmapTriplesIteratorYFOQ.java:158)
	at org.rdfhdt.hdt.triples.impl.BitmapTriplesIteratorYFOQ.<init>(BitmapTriplesIteratorYFOQ.java:77)
	at org.rdfhdt.hdt.triples.impl.BitmapTriples.search(BitmapTriples.java:239)
	at org.rdfhdt.hdtjena.solver.StageMatchTripleID.makeNextStage(StageMatchTripleID.java:140)
	at org.rdfhdt.hdtjena.solver.StageMatchTripleID.makeNextStage(StageMatchTripleID.java:53)
	at org.apache.jena.atlas.iterator.RepeatApplyIterator.hasNext(RepeatApplyIterator.java:48)
	at org.rdfhdt.hdtjena.util.IterAbortable.hasNext(IterAbortable.java:62)
	at org.apache.jena.atlas.iterator.Iter$4.hasNext(Iter.java:303)
	at org.apache.jena.sparql.engine.iterator.QueryIterPlainWrapper.hasNextBinding(QueryIterPlainWrapper.java:53)
	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:111)
	at org.apache.jena.sparql.engine.iterator.QueryIterConvert.hasNextBinding(QueryIterConvert.java:58)
	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:111)
	at org.apache.jena.sparql.engine.iterator.QueryIterDistinct.getInputNextUnseen(QueryIterDistinct.java:104)
	at org.apache.jena.sparql.engine.iterator.QueryIterDistinct.hasNextBinding(QueryIterDistinct.java:70)
	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:111)
	at org.apache.jena.sparql.engine.iterator.QueryIterSlice.hasNextBinding(QueryIterSlice.java:76)
	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:111)
	at org.apache.jena.sparql.engine.iterator.QueryIteratorWrapper.hasNextBinding(QueryIteratorWrapper.java:39)
	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:111)
	at org.apache.jena.sparql.engine.iterator.QueryIteratorWrapper.hasNextBinding(QueryIteratorWrapper.java:39)
	at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:111)
	at org.apache.jena.sparql.engine.ResultSetStream.hasNext(ResultSetStream.java:74)
	at org.apache.jena.sparql.engine.ResultSetCheckCondition.hasNext(ResultSetCheckCondition.java:59)
	at org.apache.jena.sparql.resultset.CSVOutput.format(CSVOutput.java:81)
	at org.apache.jena.query.ResultSetFormatter.outputAsCSV(ResultSetFormatter.java:624)
	at org.rdfhdt.hdtjena.cmd.HDTSparql.execute(HDTSparql.java:66)
	at org.rdfhdt.hdtjena.cmd.HDTSparql.main(HDTSparql.java:131)
```

I have tried on other HDT files generated my me and still happening.  

Regards

**Comment by MarioAriasGa** [comment]
Hi mladvladimi, I have tried with the latest version from master and this is not happening. (The query is really slow, but that's another story)

**Comment by mladvladimir** [comment]
Hi @MarioAriasGa, 
Thanks for info, it works as you said.
