### ISSUE TITLE
LOD-a-lot hdt file does not work

### ISSUE THREAD

**Issue by firmao** [rdfhdt/hdt-java#73]
I just downloaded the hdt file from http://lod-a-lot.lod.labs.vu.nl/data/LOD_a_lot_v1.hdt
Reading the file the following error appears:

> 1936 [main] ERROR org.rdfhdt.hdtjena.bindings.BindingHDTNode  - get1(?o)
java.lang.NegativeArraySizeException
	at org.rdfhdt.hdtjena.cache.DictionaryCacheArray.put(DictionaryCacheArray.java:63)
	at org.rdfhdt.hdtjena.NodeDictionary.getNode(NodeDictionary.java:127)
	at org.rdfhdt.hdtjena.NodeDictionary.getNode(NodeDictionary.java:110)
	at org.rdfhdt.hdtjena.bindings.BindingHDTNode.get1(BindingHDTNode.java:115)
	at org.apache.jena.sparql.engine.binding.BindingBase.get(BindingBase.java:121)
	at org.rdfhdt.hdtjena.bindings.BindingHDTNode.format(BindingHDTNode.java:133)
	at org.apache.jena.sparql.engine.binding.BindingBase.format1(BindingBase.java:163)
	at org.apache.jena.sparql.engine.binding.BindingBase.toString(BindingBase.java:138)
	at org.apache.jena.sparql.core.ResultBinding.toString(ResultBinding.java:91)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at TestHDT.main(TestHDT.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
java.lang.NullPointerException
	at org.rdfhdt.hdtjena.bindings.BindingHDTNode.format(BindingHDTNode.java:135)
	at org.apache.jena.sparql.engine.binding.BindingBase.format1(BindingBase.java:163)
	at org.apache.jena.sparql.engine.binding.BindingBase.toString(BindingBase.java:138)
	at org.apache.jena.sparql.core.ResultBinding.toString(ResultBinding.java:91)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at TestHDT.main(TestHDT.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)

**Also the Jena Model.size() is a negative number.**

My code:

```
public class TestHDT {
	public static void main(String[] args) throws IOException {
		File file = new File("LOD_a_lot_v1.hdt");
		HDT hdt = null;
		try {
			hdt = HDTManager.mapHDT(file.getAbsolutePath(), null);
			HDTGraph graph = new HDTGraph(hdt);
			Model model = new ModelCom(graph);
			String sparql = "select * where {?s ?p ?o} limit 10";

			Query query = QueryFactory.create(sparql);

			QueryExecution qe = QueryExecutionFactory.create(query, model);
			ResultSet results = qe.execSelect();

			String csvName = "unidomains.csv";
			int count = 0;
			System.out.println("Model.size(): " + results.getResourceModel().size());
			while (results.hasNext()) {
				QuerySolution thisRow = results.next();
				System.out.println("Row " + (++count) + ": " + thisRow);
			}
			qe.close();
		} catch (Exception e) {
			e.printStackTrace();
		} finally {
			if (hdt != null) {
				hdt.close();
			}
		}
	}
}
```

**Comment by wouterbeek** [comment]
See my answer in the other repository where this question was posted: https://github.com/rdfhdt/LOD-a-lot-www/issues/1

**Comment by wouterbeek** [comment]
I'm not 100% sure since I'm more familiar wit the C++ implementation, but @MarioAriasGa created the 64-bit branch: https://github.com/rdfhdt/hdt-java/tree/long-dict-id

**Comment by MarioAriasGa** [comment]
Yes, indeed you need the long-dict-id branch for the LOD-a-lot. Did you try that?

**Comment by bjonnh** [comment]
@MarioAriasGa have there been discussions to include that in the main distribution or make it available somehow with a configuration option. Also could it be added to the website's documentation?

**Comment by mielvds** [comment]
@bjonnh can this be closed?
