### ISSUE TITLE
Exception when processing DBpedia

### ISSUE THREAD

**Issue by jerdeb** [rdfhdt/hdt-java#76]
I have recently added an HDTProcessor in Luzzu, however, I am getting a GC overhead limit exceeded when parsing the HDT version of DBpedia (the index was used as well):

```
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.lang.Long.valueOf(Long.java:840)
	at pl.edu.icm.jlargearrays.LongLargeArray.get(LongLargeArray.java:148)
	at org.rdfhdt.hdt.compact.sequence.SequenceLog64Big.getField(SequenceLog64Big.java:129)
	at org.rdfhdt.hdt.compact.sequence.SequenceLog64Big.get(SequenceLog64Big.java:239)
	at org.rdfhdt.hdt.dictionary.impl.section.PFCDictionarySectionBig.extract(PFCDictionarySectionBig.java:344)
	at org.rdfhdt.hdt.dictionary.impl.BaseDictionary.idToString(BaseDictionary.java:219)
	at org.rdfhdt.hdtjena.NodeDictionary.getNode(NodeDictionary.java:114)
	at io.github.luzzu.io.impl.HDTProcessor.startProcessing(HDTProcessor.java:95)
	at io.github.luzzu.io.AbstractIOProcessor.processorWorkFlow(AbstractIOProcessor.java:134)
	at io.github.luzzu.communications.resources.v4.AssessmentResource$1.call(AssessmentResource.java:210)
	at io.github.luzzu.communications.resources.v4.AssessmentResource$1.call(AssessmentResource.java:206)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I implemented the processor [1] in a streaming fashion, and the error seems to be in this line: `	Node o = this.nodeDictionary.getNode(this.hdtDictionary.stringToId(triple.getObject(), TripleComponentRole.OBJECT), TripleComponentRole.OBJECT);`

Do you know what might have triggered that exception? 

Thanks!
Jeremy

[1] https://gist.github.com/jerdeb/60ce2a8c07413c0a3b6c816124590e57

**Comment by mielvds** [comment]
Note that something like that already exists: https://github.com/rdfhdt/hdt-java/blob/master/hdt-java-core/src/main/java/org/rdfhdt/hdt/hdt/impl/TempHDTImporterOnePass.java

About your issue, could be an issue with the 64bit index. Or maybe your dataset is simply too big. Did you specifiy a larger GC?
