### ISSUE TITLE
java.lang.IllegalArgumentException: (?u,null)

### ISSUE THREAD

**Issue by ofilangi** [rdfhdt/hdt-java#80]
Hello,
Next a generation of a hdt file with https://github.com/rdfhdt/hdt-docker and my own turtle file, I used this hdt file with hdt-fuseki (command : `./bin/hdtEndpoint.sh --hdt ./ALL.hdt /dataset`) . the sparql endpoint works well with some sparql command i used but throw an exception for the following sparql request

`curl -H "Accept: application/json" http://<myserver>:3030/dataset/sparql --data-urlencode query='PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> SELECT ?u ?l ?p WHERE { VALUES ?u { <fr.mgdis.odata.data.plagesBREfrType> } OPTIONAL { ?u rdfs:label ?l . BIND (rdfs:label AS ?p) } }'`

server logs:

`
15:38:36 INFO  [25] Query = PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> SELECT ?u ?l ?p WHERE { VALUES ?u { <fr.mgdis.odata.data.plagesBREfrType> } OPTIONAL { ?u rdfs:label ?l . BIND (rdfs:label AS ?p) } }
15:38:36 WARN  [25] RC = 500 : (?u,null)
java.lang.IllegalArgumentException: (?u,null)
        at org.rdfhdt.hdtjena.bindings.BindingHDTId.put(BindingHDTId.java:79)
        at org.rdfhdt.hdtjena.solver.HDTSolverLib$3.apply(HDTSolverLib.java:202)
        at org.rdfhdt.hdtjena.solver.HDTSolverLib$3.apply(HDTSolverLib.java:178)
        at org.apache.jena.atlas.iterator.Iter$4.next(Iter.java:308)
        at org.apache.jena.atlas.iterator.RepeatApplyIterator.hasNext(RepeatApplyIterator.java:47)
        at org.rdfhdt.hdtjena.util.IterAbortable.hasNext(IterAbortable.java:62)
        at org.apache.jena.atlas.iterator.Iter$4.hasNext(Iter.java:303)
        at org.apache.jena.sparql.engine.iterator.QueryIterPlainWrapper.hasNextBinding(QueryIterPlainWrapper.java:53)
        at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:111)
        at org.apache.jena.sparql.engine.iterator.QueryIterProcessBinding.hasNextBinding(QueryIterProcessBinding.java:66)
        at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:111)
        at org.apache.jena.sparql.engine.iterator.QueryIterDefaulting.hasNextBinding(QueryIterDefaulting.java:54)
        at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:111)
        at org.apache.jena.sparql.engine.iterator.QueryIterRepeatApply.hasNextBinding(QueryIterRepeatApply.java:74)
        at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:111)
        at org.apache.jena.sparql.engine.iterator.QueryIterConvert.hasNextBinding(QueryIterConvert.java:58)
        at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:111)
        at org.apache.jena.sparql.engine.iterator.QueryIteratorWrapper.hasNextBinding(QueryIteratorWrapper.java:39)
        at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:111)
        at org.apache.jena.sparql.engine.iterator.QueryIteratorWrapper.hasNextBinding(QueryIteratorWrapper.java:39)
        at org.apache.jena.sparql.engine.iterator.QueryIteratorBase.hasNext(QueryIteratorBase.java:111)
        at org.apache.jena.sparql.engine.ResultSetStream.hasNext(ResultSetStream.java:74)
        at org.apache.jena.sparql.engine.ResultSetCheckCondition.hasNext(ResultSetCheckCondition.java:59)
        at org.apache.jena.fuseki.servlets.SPARQL_Query.executeQuery(SPARQL_Query.java:297)
        at org.apache.jena.fuseki.servlets.SPARQL_Query.execute(SPARQL_Query.java:252)
        at org.apache.jena.fuseki.servlets.SPARQL_Query.executeWithParameter(SPARQL_Query.java:205)
        at org.apache.jena.fuseki.servlets.SPARQL_Query.perform(SPARQL_Query.java:100)
        at org.apache.jena.fuseki.servlets.SPARQL_ServletBase.executeLifecycle(SPARQL_ServletBase.java:227)
        at org.apache.jena.fuseki.servlets.SPARQL_ServletBase.executeAction(SPARQL_ServletBase.java:204)
        at org.apache.jena.fuseki.servlets.SPARQL_ServletBase.execCommonWorker(SPARQL_ServletBase.java:186)
        at org.apache.jena.fuseki.servlets.SPARQL_ServletBase.doCommon(SPARQL_ServletBase.java:79)
        at org.apache.jena.fuseki.servlets.SPARQL_Query.doPost(SPARQL_Query.java:60)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1496)
        at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:82)
        at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:256)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:229)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
        at org.eclipse.jetty.server.Server.handle(Server.java:370)
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
        at org.eclipse.jetty.server.BlockingHttpConnection.handleRequest(BlockingHttpConnection.java:53)
        at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
        at org.eclipse.jetty.server.BlockingHttpConnection.handle(BlockingHttpConnection.java:72)
        at org.eclipse.jetty.server.nio.BlockingChannelConnector$BlockingChannelEndPoint.run(BlockingChannelConnector.java:298)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
        at java.lang.Thread.run(Thread.java:748)
15:38:36 INFO  [25] 500 (?u,null) (5 ms)
`

**Comment by mielvds** [comment]
@ofilangi did #120 fix this?
